# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod Properties
mod_version=2.1.0
maven_group=net.fabric_extras
archives_name=shield_api
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
minecraft_version_compat=1.21

# Fabric Properties
fabric_loader_version = 0.16.5
fabric_api_version=0.115.6+1.21.1

# NeoForge Properties
neoforge_version=21.1.201
yarn_mappings_patch_neoforge_version=1.21+build.4
forgified_fabric_api_version=0.115.6+2.1.1+1.21.1