modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "shield_api"
version = "${version}"
displayName = "ShieldAPI"
authors = "TheRedBrain"
description = '''
Creating shields with custom models was never easier!
'''
logoFile = "icon.png"

[[dependencies.shield_api]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.shield_api]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "shield_api.mixins.json"
